import { defineCollection } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';

// Source the canonical repo-root docs/ tree via the `src/content/docs` symlink.
// Starlight's docsLoader() (rather than a raw glob with a custom base) is required
// for the autogenerated sidebar to populate: Starlight derives sidebar directories
// from the entry path relative to src/content/docs, not from the loader's base.
export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
};
